config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#show'
  resources :challenges, only: [:new, :create, :show] do
    member do
      get :join
      post :started
    end
  end
  resources :participations, only: [:show, :create]
  resources :progressions, only: [:index, :create, :update, :destroy] do
    post :done, on: :member
  end
end
# patch "progression/:id", to: "progression#update"
# rajouter les crud

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :participations, dependent: :destroy
  has_one_attached :photo


  validates :title, :description, :start_date, :frequency, presence: true
  # validates :end_date, presence: true, date: { after_or_equal_to: :start_date }
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :challenge
  belongs_to :user
  has_many :progressions, dependent: :destroy
end

app/models/progression.rb
class Progression < ApplicationRecord
  belongs_to :participation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :participations, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description, :photo, :total_points])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :photo, :total_points])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[show started progression_count_current_user total_point_challenge]

  def index
    @challenges = Challenge.all
  end

  def show
    @time_left = (@challenge.end_date - Date.today).to_i
    @challenge.total_time = (@challenge.end_date - @challenge.start_date)
    @participations = @challenge.participations
    @users = @participations.map(&:user)
    @creator = @challenge.participations.first.user
    @progression_count_current_user = progression_count_current_user
    @total_points_count = total_points_challenge
  end

  def progression_count_current_user
    user = current_user
    @progression_count = 0
    user.participations.each do |participation|
      if participation.challenge_id == @challenge.id
        participation.progressions.each do |progression|
          if progression.done
            @progression_count += 1
          end
        end
      end
    end
    return @progression_count
  end

  def total_points_challenge
    user = current_user
    @total_points_count = 0
    user.participations.each do |participation|
      if participation.challenge_id == @challenge.id
        participation.progressions.each do |progression|
          if progression.done
            @total_points_count += 1
          end
        end
      end
    end
    return @total_points_count
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
    if @challenge.save
      total_time = (@challenge.end_date - @challenge.start_date)
      @challenge.update(total_time: total_time, started: false)
      @user = current_user
      participation = Participation.new(user: @user, challenge: @challenge)
      participation.save
      create_progressions(@challenge, participation)
      redirect_to challenge_path(@challenge)
    else
      render :show
    end
  end

  def join
    redirect_to challenge_path
  end

  def started
    @challenge.update!(started: true)
    head :ok
  end

  private

  def challenge_params
    params.require(:challenge).permit(:start_date, :end_date, :title, :photo, :description, :frequency)
  end

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def create_progressions(challenge, participation)
    case challenge.frequency
    when "Quotidiennement"
      daily_progression(challenge, participation)
    when "Une fois par semaine"
      weekly_progression(challenge, participation)
    when "Une seule fois à la fin"
      monthly_progression(challenge, participation)
    end
  end

  def daily_progression(challenge, participation)
    duration = challenge.total_time
    date = challenge.start_date - 1
    while duration.positive?
      new_date = date += 1
      Progression.create!(date: new_date, participation: participation, points: 10, done: false)
      duration -= 1
    end
  end

  def weekly_progression(challenge, participation)
    duration = challenge.total_time
    date = challenge.start_date - 7
    while duration.positive?
      new_date = date += 7
      Progression.create!(date: new_date, participation: participation, points: 50, done: false)
      duration -= 7
    end
  end

  def monthly_progression(challenge, participation)
    new_date = challenge.end_date
    Progression.create!(date: new_date, participation: participation, points: 150, done: false)
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def show
    @participation = Participation.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @challenge = Challenge.find(params[:challenge_id])
    @participation = Participation.new(user: @user, challenge: @challenge)
    if @participation.save
      create_progressions(@challenge, @participation)
    end
  end

  private

  def create_progressions(challenge, participation)
    case challenge.frequency
    when "Quotidiennement"
      daily_progression(challenge, participation)
    when "Une fois par semaine"
      weekly_progression(challenge, participation)
    when "Une seule fois à la fin"
      monthly_progression(challenge, participation)
    end
  end

  def daily_progression(challenge, participation)
    duration = challenge.total_time
    date = challenge.start_date - 1
    while duration.positive?
      new_date = date += 1
      Progression.create!(date: new_date, participation: participation, points: 10, done: false)
      duration -= 1
    end
  end

  def weekly_progression(challenge, participation)
    duration = challenge.total_time
    date = challenge.start_date - 7
    while duration.positive?
      new_date = date += 7
      Progression.create!(date: new_date, participation: participation, points: 50, done: false)
      duration -= 7
    end
  end

  def monthly_progression(challenge, participation)
    new_date = challenge.end_date
    Progression.create!(date: new_date, participation: participation, points: 150, done: false)
  end
end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController
  def done
    progression = Progression.find(params[:id])
    progression.update!(done: true)
    user = progression.participation.user
    new_points = user.total_points + progression.points
    user.update!(total_points: new_points)
    head :ok
  end

  def new
    @progression = Progression.new
  end

  def create
    progression = Progression.find(params[:id])
    progression.save
  end

  def destroy
    progression = Progression.find(params[:id])
    progression.destroy
    redirect_to root_path
  end

  def progression_params
    params.require(:progression).permit(:date, :done, :points, :new_points)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @participations = @user.participations.includes(:progressions)
    @challenges = @participations.map(&:challenge)
  end

  private

  def user_params
    params.require(:user).permit(:name, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/challenges/_show_finished.erb
<div class='challenge-description my-4 d-flex flex-column align-items-center'>
  <div class="mt-5 mb-2">
    <h2 class="card-blue">"<%= @challenge.title %>" est terminé</h2>
  </div>
</div>
  <div>
    <p class="pb-3"><strong>Terminé depuis le : </strong><%= ConvertDate.new(date: @challenge.end_date.strftime('%a %d %b')).call %>
    <br><strong>Durée totale :</strong> <%= @challenge.total_time %> jours.</p>
    <div class="card3 text-center my-4">
      <p>Tu as effectué <%= @progression_count_current_user %> jours de challenge, et remporté <%= @total_points_count %> points!</p>
    </div>
  <p class="my-4"><small><em>Nostalgique ? Tu peux toujours recréer ce challenge, ou en inventer un autre <%= link_to "ici", new_challenge_path %>!<em></small></p>
  </div>
</div>

app/views/challenges/_show_not_started.html.erb
<div class='challenge-description my-5 d-flex flex-column align-items-center'>
  <div class="mt-5 mb-2">
      <h1 id="title", class="card-blue" data-challenge="<%= @challenge.title %>">
        "<%= @challenge.title %>" en préparation...
      </h1>
  </div>
  <div class="card-not-center mt-4">
    <p
      id="debut"
      data-challenge-debut="<%= @challenge.total_time %>"
      data-challenge-time-left="<%= @time_left %>">
      <strong>Début:</strong> <%= ConvertDate.new(date: @challenge.start_date.strftime('%a %d %b')).call %>.
      <br><strong>Durée:</strong> <%= @challenge.total_time %> jours.
    </p>
  </div>
  <% if current_user == @creator %>
    <p>"<%= @challenge.description %>"</p>

    <div class="cards-color card3 text-center my-4"
      data-controller="share"
      data-share-id-value= <%= @challenge.id %>
      data-share-title-value= <%= @challenge.title %>
      data-share-creator-value= <%= @creator.name %>>
        <p class="pb-3">Prêt à récolter des points et défier tes potes?</p>
        <p class= "btn btn-primary" data-action="click->share#shareLink"> Partage ton lien! </p>
    </div>
  <% else %>
    <div class="card3 text-center my-4">
      <div data-controller='enter-challenge'
        data-enter-challenge-target="cardEnter"
        data-enter-challenge-create-url-value= "<%= participations_path %>"
        data-enter-challenge-user-id-value= "<%= current_user.id %>"
        data-enter-challenge-challenge-id-value= "<%= @challenge.id %>">

        <%# CAS: invitation reçue au challenge %>
        <p data-enter-challenge-target="canard">Veux-tu y participer?</p>
        <button data-enter-challenge-target="poule" class="btn btn-go btn-primary" data-action="click->enter-challenge#accept">
          Let's go!
        </button>
        <button data-enter-challenge-target="oie" class="btn btn-nop btn-primary" data-action="click->enter-challenge#refuse">
          Nope
        </button>
      </div>
    </div>
  <% end %>
  <div class="cards-color card3 my-3  class="d-flex justify-content-around">
    <h5>Participant·e·s inscrit·e·s:</h5>
    <ul class="d-flex justify-content-around">
      <% @users.each do |user| %>
        <div class="d-flex flex-column justify-content-center">
          <li><%= cl_image_tag user.photo.key, height: 200, width: 200, crop: :fill, class:"avatar2" %></li>
          <li><strong><%= user.name %></strong></li>
        </div>
      <% end %>
    </ul>

      <%# CAS: bouton "lancer le challenge" %>
    <% if current_user == @creator %>
      <div data-controller="started"
        data-started-update-url-value="<%=  started_challenge_path(@challenge) %>">
        <button id="launch2" class="btn mt-2 btn-primary" data-action="click->started#status">
          C'est parti !
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/challenges/_show_started.erb
<div class='challenge-description mt-5 d-flex flex-column align-items-center'>
  <div class="mt-5 mb-2">
    <h1 class="card-blue">"<%= @challenge.title.capitalize %>" est lancé !</h1>
  </div>
  <div class="cards-color card-under-blue my-5">
    <p> Wouhou! Tu participes actuellement à ce challenge !</p>
    <i class="fas fa-rocket i1"></i>
    <i class="fas fa-rocket i2"></i>
    <i class="fas fa-rocket i3"></i>
    <p class="text-center my-2"><strong>Date de fin:</strong> <%= ConvertDate.new(date: @challenge.end_date.strftime('%a %d %b')).call %>.</p>
    <p>Il te reste <%= @time_left %> jours pour te surpasser!</p>
  </div>
  <div class="challenge-description">
    <p>"<%= @challenge.description %>"</p>
  </div>
  <div class="cards-color card4 text-center my-4">
    <h5>Tou·te·s les participant·e·s</h5>
    <ul class="d-flex justify-content-around">
      <% @users.each do |user| %>
        <div class="d-flex flex-column justify-content-center">
          <li><%= cl_image_tag user.photo.key, class:"avatar2" %></li>
          <li><%= user.name.capitalize %></li>
        </div>
      <% end %>
    </ul>
  </div>

  <div class="bottom-challenge">
    <h5 class="progression-title text-white text-center">Progressions</h5>
    <% @participations.each do |participation| %>
        <% @progression_count = 0 %>
        <% participation.progressions.each do |progression| %>
          <% if progression.done %>
            <% @progression_count += 1 %>
          <% end %>
        <% end %>
        <% ratio = @progression_count*100/@challenge.total_time%>
        <div class="back-blue w-100">
          <div class="d-flex justify-content-between">
            <div class="flex-grow-1 text-end pe-3">
              <p><%= participation.user.name.capitalize %></p>
            </div>
            <div class="me-5">
              <span><%= image_tag "#{ratio.round(-1)}.svg" %></span>
            </div>
          </div>
        </div>
    <% end %>
    <div class="back-blue w-100 pb-4">
    </div>
  </div>
</div>

app/views/challenges/new.html.erb
  <div class="container2">
    <div >
      <div class="col-12 d-flex justify-content-center">
        <div class='col-12'>
          <div class="fond-new-challenge">
            <h1 id="title-challenge-form" class="text-center">Créé ton challenge!</h1><br>
          </div>
              <div class="centered col-10">
            <%= simple_form_for(@challenge) do |f| %>
                <%= f.input :title,
                            label: "Trouve un super titre!",
                            autofocus: true %>
                <%= f.input :description,
                label: "Décris le challenge à tes potes:" %>
                <%= f.input :start_date, as: :date, html5: true,
                label: "Vous commencez quand?" %>
                <%= f.input :end_date, as: :date, html5: true,
                label: "Et la date de fin?" %>
                <p><%= "A quelle fréquence veux-tu effectuer ce challenge ?" %></p>
                <%= f.select :frequency,
                [ 'Quotidiennement','Une fois par semaine','Une seule fois à la fin' ],
                prompt: 'Fais ton choix' %>
                <br>
                <br>
                <%= f.submit "Enregistrer ce challenge", class:"btn mb-3 ms-2", style:"width: 95%" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/challenges/show.html.erb
<div class="top-show-challenge">
  <div class="mx-3">
    <div class="col-12 d-flex">
      <div class="container">
        <% if @challenge.started %>
          <% if @challenge.end_date < Date.today %>
            <%= render 'show_finished' %>
          <% else %>
            <%= render 'show_started' %>
          <% end %>
        <% else %>
            <%= render 'show_not_started' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge-accepted - Your goals become a game!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title><%= meta_title %></title>
    <link rel="manifest" href="/manifest.webmanifest">

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless current_page?(new_user_session_path) || current_page?(user_session_path) || current_page?(new_user_registration_path) || current_page?(root_path) || current_page?(new_challenge_path) %>
      <%= render 'shared/home-button' %>
    <% end %>
    <%= render 'shared/flashes' %>


    <%= yield %>

  </body>

</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home-button.html.erb
<a href= "<%= root_path %>" ><i class="fas fa-home position-absolute"></i></a>

app/views/users/show.html.erb
<div class="top-show-user">
  <div class="flexbox">
    <div>
      <%= cl_image_tag @user.photo.key, id: "avatar" %>
    </div>
    <div class="text-center" id="title">
      <h1 class="title">CHALLENGE ACCEPTED</h1>
    </div>
    <div id="log-out">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
      <% end %>
    </div>
  </div>
  <div class="greeting">
    <h2>Hey,</h2>
    <h2><%= @user.name.capitalize %> !</h2>
  </div>
</div>
<div class="container">
  <div class="d-flex flex-column text-center points my-2">
    <i class="fas fa-trophy"></i>
    <p class="text-larger"><strong><%= @user.total_points %></strong> points</p>
    <% if @user.total_points.positive? %>
      <p class="mb-2">Wow, tu te surpasses!</p>
    <% else %>
      <p class="mb-2">Accomplis une progression pour gagner tes premiers points !</p>
    <% end %>
  </div>
  <div class='validation-progression'>
    <h3 class="text-center pt-3">Tes progressions à valider :</h3>
    <div class="my-3">
      <% @challenges.each do |challenge| %>
        <% if challenge.end_date > Date.yesterday %>
          <% challenge.participations.each do |participation| %>
            <% participation.progressions.each do |progression| %>
              <% if progression.done == false && progression.date < Date.tomorrow %>
                <% if participation.user_id == current_user.id %>
                  <div class="progression_card d-flex justify-content-center"
                    data-controller="validate-progression"
                    data-validate-progression-update-url-value="<%= done_progression_path(progression) %>">
                    <div class="w-100 d-flex justify-content-between">
                      <div class="body4 flex-grow-1">
                        <h3 class="mb-2"><strong><%= challenge.title.capitalize %></strong></h3>
                        <p class="no-margin">Le <%= ConvertDate.new(date: progression.date.strftime('%a %d %b')).call %></p>
                      </div>
                      <div class="d-flex align-items-center">
                        <button class="btn btn-valid" data-action="click->validate-progression#validate">
                          <i class="fas fa-check d-flex justify-content-center"></i>
                        </button>
                        <div class="ms-2">
                          <%= link_to progression_path(progression), class: 'btn btn-not-valid', method: :delete do %>
                            <i class="fas fa-times d-flex justify-content-center"></i>
                          <% end %>
                        </div>
                      </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="d-flex justify-content-center my-3 mb-2 btn-go" >
  <%= link_to "Crée un challenge!", new_challenge_path, class: "btn mt-3"%>
</div>
<div>
  <h3 class="mt-3 mb-2 ms-1">Tes challenges en cours:</h3>
  <div class="scroll ms-1">
    <% @challenges.each do |challenge| %>
      <% if challenge.end_date > Date.yesterday %>
        <div class="card2" >
           <% time_left = (challenge.end_date - Date.today).to_i %>
            <div class="card-body">
              <%= link_to challenge_path(challenge) do %>
                <h3 class="dark-font text-center"><strong><%= challenge.title.capitalize %></strong></h3>
                <div class="dark-font">Se termine dans : <%= time_left %> jours</div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <h3 class="mt-3 mb-2 ms-1">Tes anciens challenges :</h3>
    <ul class="scroll ms-1">
      <% @challenges.each do |challenge| %>
        <% if challenge.end_date < Date.today %>
          <div class="card-finish">
            <li>
              <div class="card-body">
                <%= link_to challenge_path(challenge) do %>
                  <h3 class="dark-font text-center"><strong><%= challenge.title.capitalize %></strong></h3>
                  <p>Terminé depuis le <%= ConvertDate.new(date: challenge.end_date.strftime('%a %d %b')).call %></p>
                <% end %>
              </div>
            </li>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>